### PR TITLE
Update updateexec

### PR DESCRIPTION
**Pull request by CnCRAZER**

### CODE REVIEW

**Comment by devo1929** [comment]
What's the reason for removing these lines?

**Comment by CnCRAZER** [comment]
> What's the reason for removing these lines?

After each update the files are removed due to case sensitivities. Force update redownloads the maps but next update to client removes them again.

**Review by alexp8 — DISMISSED** [review]

**Comment by devo1929** [comment]
@CnCRAZER I think you still need to update this PR, right? You need to take the lines that you removed from the `updateexec` file here and add them to the `preupdateexec` file.

**Comment by CnCRAZER** [comment]
> @CnCRAZER I think you still need to update this PR, right? You need to take the lines that you removed from the `updateexec` file here and add them to the `preupdateexec` file.

I think I've done it now. Let me know if it's still incorrect/wrong.

**Review by devo1929 — APPROVED** [review]

**Comment by devo1929** [comment]
For some reason, Github is saying there's a conflict and so this cannot be merged. Can you rebased your branch locally with the latest cncnet develop branch?

**Pull request closed without merging**
