### PR TITLE
Update Brutal AI.ini

### PR DESCRIPTION
**Pull request by CnCRAZER**
Fix taskforces / teamtypes / scriptactions from overriding maps with pre-existing taskforces / teamtypes / scriptactions.

This eliminates the crash with EIP 006F1FC6

### CODE REVIEW

**Review by alexlambson — APPROVED** [review]
I approve the new declarations. Unfortunately I'm not good enough at the game to actually review the difficulty though. I got stomped.

**Comment by hxazgalor** [comment]
Personally not a fan of the new Brutal AI adjustments. The sheer number of units they mass in the early game is impossible to beat, even with a stack of Rhinos while still juggling with an early eco. Even the AI ally is useless against them. Might need more tweaks to make it fair, or just revert it to vanilla Brutal AI settings. People can always play with mods if they want a bulldozing AI.

**Comment by CnCRAZER** [comment]
The prior brutal ai barely did anything above hard ai. I bet in blind tests the average player couldn't tell a difference.


However, brutal ai affects all three difficulties a bit differently. You can try easy + brutal ai to play a slower pace than hard + brutal ai

**Comment by hxazgalor** [comment]
In that case, it might be better to remove their ability to build multiple units simultaneously from each separate production building they have (specifically, Barracks and Warfacs). Could implement factory bonus for them instead, or have them plan larger attack waves without the need for multibuild. Even on Medium Brutal, it's still a nightmare to deal with.

**Comment by alexlambson** [comment]
Maybe we should rename it to "Advanced AI" or something to make it more clear that it can be used with easy and normal

**Comment by Saint146** [comment]
Just wanted to comment that I was pleasantly surprised with how I got owned in my casual skirmish :D
I think an advanced AI is very nice to have in "base" game without any additional mods.

Maybe it can be a combobox with various AI to choose from and to allow to add more (Vanilla/Advanced/Brutal/etc)

**Comment by CnCRAZER** [comment]
> Just wanted to comment that I was pleasantly surprised with how I got owned in my casual skirmish :D I think an advanced AI is very nice to have in "base" game without any additional mods.
> 
> Maybe it can be a combobox with various AI to choose from and to allow to add more (Vanilla/Advanced/Brutal/etc)



> Maybe we should rename it to "Advanced AI" or something to make it more clear that it can be used with easy and normal

#389 :)

**Pull request merged**
