### PR TITLE
Burg/May YR Update

### PR DESCRIPTION
**Pull request by alexp8**
### May YR Map Pack Update

- MPMaps.ini generated via https://github.com/ChronoVortex/YRMapsUpdater/releases
- versionconfig.ini updated to include new files
- YR client run locally / tested each map appears/renders/plays successfully

### Client updates:
-Update Map Renderer to 2.4.0.0
-Update client binaries and second-stage updater to the latest version
-Update client sounds and graphics

-Yuri's Rebalance patch replaced with **Yuri's Revenge Rebalanced** developed by RaVaGe

### Adding following maps:
- 2_andalusia
- 2_delta_vega
- 2_prime_harbor
- 2_venice
- 2_the_path_more_travelled
- 2_divide_freezes_over_le
- 4_dorado_descent
- 4_tiburon
- 4_montana_dmz_le
- 6_whistler
- 8_invasion
- 8_fountain_of_youth
- 8_the_eye
- 8_highway_borealis
- 8_death_valley_girl_4v4
- 8_desert_island_4v4
- 6_grand_gulch

**Updating** below maps and replacing existing:
- 4_bull_run_le
- 2_malibu_cliffs_le
- 4_country_swing_le
- 8_cliffside_slide
- 8_corwick_forest
- 4_desert_island_le
- 4_frostbite_le

Updated "INI\Map CodeCompetitive Balance.ini" game mode to reflect the competitive options currently enabled in YR QM.

### CODE REVIEW

**Review by Metadorius — APPROVED** [review]
Needs versionconfig updates to be merged.

**Comment by pzhlkj6612** [comment]
Hello @alexp8 . It seems that https://forums.cncnet.org/topic/11738-yuris-revenge-rebalanced-20/ cannot be accessed:

> (!)
> Sorry, there is a problem
>
> We could not locate the item you are trying to view.
> Error code: 2F173/O

**Comment by alexp8** [comment]
Hi this Form Post is completed but hidden at the moment but will be published right after the update goes live.

**Comment by pzhlkj6612** [comment]
OK, got it. Thank you for your replying.

**Pull request merged**
