### PR TITLE
Update Brutal AI.ini

### PR DESCRIPTION
**Pull request by CnCRAZER**
**Compatability Changes:**

- TaskForces / TeamTypes / ScriptTypes / AITriggerTypes changed to have custom name scheme to prevent any potential conflict with maps which might have pre-existing TaskForces / TeamTypes / ScriptTypes / AITriggerTypes.
- IgnoreGlobalAiTriggers is now set to yes. Anything from aimd.ini will be ignored and these will be used instead.

**General AI changes:**

- Reduced AIBaseSpacing from 2 to 1.0. @Steff833 Factories and Refineries now have WantsExtraSpace=yes to compensate.
- Third warfactories and extra naval yards are now locked behind the AI producing battle labs to help ensure superweapon creation and higher techlevel TeamTypes.
- Naval teams for Allied and Soviet have been slightly increased in size and a slight change in their script types to try and have them more 'aggressive'.
- Various script changes to 'attack anything' and make more teamtypes have 'aggressive=yes' and 'suicide=yes'.

**Soviet AI:**

- Boris has been added to a couple teams.
- AI now attempts to make more siege choppers than regular. 
- AI no longer fills entire flaktracks with Ivans. Thanks to Nizzy for the constant complaints about this :P
- TaskForces with Conscripts have been reduced from previous changes.
- Now builds Service Depot.

**Allied AI:**

- France now builds more than one Grand Cannon. 
- PillBox defensive construction has been altered to try and not build as many.
- Now builds Service Depot.
- Most defensive and attack teams have had TaskForce sizes increased to make it more balanced with Soviet AI.

### CODE REVIEW

**Comment by Steff833** [comment]
Whats with your setting AIBaseSpacing=2 I already mentioned. I tested some maps. And in most maps there is not so much space for building a full base. For example naval maps.

The AI is not human and cant adjust. So it`ll stop producing buildings if no space is there.

1 = standard and I think it works better. Also the AI placed his defends (Anti Air, Prism Towers and Tesla Coils) closer and more effective and not so spreaded wide. So for the player it is more of a challenge to overun their bases.

**Comment by CnCRAZER** [comment]
> Whats with your setting AIBaseSpacing=2 I already mentioned. I tested some maps. And in most maps there is not so much space for building a full base. For example naval maps.
> 
> 
> 
> The AI is not human and cant adjust. So it`ll stop producing buildings if no space is there.
> 
> 
> 
> 1 = standard and I think it works better. Also the AI placed his defends (Anti Air, Prism Towers and Tesla Coils) closer and more effective and not so spreaded wide. So for the player it is more of a challenge to overun their bases.

Am going to do considerable testing with this today

**Comment by CnCRAZER** [comment]
> Whats with your setting AIBaseSpacing=2 I already mentioned. I tested some maps. And in most maps there is not so much space for building a full base. For example naval maps.
> 
> The AI is not human and cant adjust. So it`ll stop producing buildings if no space is there.
> 
> 1 = standard and I think it works better. Also the AI placed his defends (Anti Air, Prism Towers and Tesla Coils) closer and more effective and not so spreaded wide. So for the player it is more of a challenge to overun their bases.

Found a good way to make this work. Testing so far has been good. The spacing is now 1.

**Comment by pzhlkj6612** [comment]
> Found a good way to make this work. Testing so far has been good. The spacing is now 1.

cfcc95ff407a1109efb269dd952a93d606b2a5d3

I think `WantsExtraSpace=yes` is a reasonable workaround! More tests on various maps are still required, though.

**Comment by CnCRAZER** [comment]
> > Found a good way to make this work. Testing so far has been good. The spacing is now 1.
> 
> 
> 
> cfcc95ff407a1109efb269dd952a93d606b2a5d3
> 
> 
> 
> I think `WantsExtraSpace=yes` is a reasonable workaround! More tests on various maps are still required, though.

The third WarFactories and second naval yards are also locked behind the AI making battle labs too, in order to help make sure they tech up

**Comment by pzhlkj6612** [comment]
> ... are also locked behind the AI making battle labs too...

You mean using `Prerequisite=xxx`?

> AI players also ignore all [Prerequisite](https://modenc.renegadeprojects.com/Prerequisite) settings except [TechLevel](https://modenc.renegadeprojects.com/TechLevel) on all other objects, they build objects in the order dictated by the [ai(md).ini](https://modenc.renegadeprojects.com/Ai.ini) file ...
> 
> *from: https://modenc.renegadeprojects.com/The_Prerequisite_System#Prerequisite_Groups*

I haven't played YR for a long time, so the actual behavior is fuzzy to me, though.

**Comment by CnCRAZER** [comment]
> > ... are also locked behind the AI making battle labs too...
> 
> 
> 
> You mean using `Prerequisite=xxx`?
> 
> 
> 
> > AI players also ignore all [Prerequisite](https://modenc.renegadeprojects.com/Prerequisite) settings except [TechLevel](https://modenc.renegadeprojects.com/TechLevel) on all other objects, they build objects in the order dictated by the [ai(md).ini](https://modenc.renegadeprojects.com/Ai.ini) file ...
> 
> > 
> 
> > *from: https://modenc.renegadeprojects.com/The_Prerequisite_System#Prerequisite_Groups*
> 
> 
> 
> I haven't played YR for a long time, so the actual behavior is fuzzy to me, though.
> 
> 

Copy the code into a map file and see. 

https://www.twitch.tv/videos/2298168759

**Comment by pzhlkj6612** [comment]
> Copy the code into a map file and see.

No testing environment on my PC, sorry.

> https://www.twitch.tv/videos/2298168759

Interesting. I've watched your recording and didn't see 3rd WarFactories before building battle labs. I think I have to test it by myself first...

**Comment by Steff833** [comment]
After your latest changes I noticed the AI also now builds amphibious transports. But unfortunately they are always empty. Is it possible to give the AI the ability to fill them with assault units? For example tanks? I know in the past there were AI mods out there where exact that happened and the AI tried to capture my Island with an amphibious Invasion. I believe it was this mod here but Im not so sure. https://forums.cncnet.org/topic/7959-red-alert-2yr-ai-improvement-mod-update-1210622-compatible-with-cnc-client-now/

**Review by alexp8 — APPROVED** [review]

**Pull request merged**
