### PR TITLE
add two new options to make the game easier.

### PR DESCRIPTION
**Pull request by LeuisKen**
Hi, I'm a player who used to play survival games. It would be great if we can add this two options.

### CODE REVIEW

**Comment by CnCRAZER** [comment]
As a map maker who's enabled auto repair on every map I've ever made, this would be a cool additional feature that could be applied to maps at the discretion of the host.

But also, as a map maker whose found a balance of BuildSpeed=X with MultipleFactory=X values that I prefer to be used in the maps I create, I feel the instant build feature might be a lazy way to cheese/win these maps with brute force and potential unit spam instead of having to edit the .map file every time.. mixed feelings about this one. Just my two cents

**Comment by LeuisKen** [comment]
@CnCRAZER Yes, I'm the lazy player. I just want this instant build after a few failure. : )

**Comment by LeuisKen** [comment]
@devo1929 @GrantBartlett @alexp8 
It would be super appreciated if someone can give some feedback here.

**Comment by alexp8** [comment]
Can you have these options force disabled for every game mode except survival @LeuisKen 

In MPMaps.ini, every game mode can force enable/disable options.
e.g. https://github.com/CnCNet/cncnet-yr-client-package/blob/4b78a704c8992fc309205c4652baa590f03efec6/package/INI/MPMaps.ini#L64

**Comment by LeuisKen** [comment]
@alexp8 Cool. Code updated. I think some of the game mode is reasonable to let the host to make the decision. Looking forward to any feedback. : )

**Comment by LeuisKen** [comment]
Hi, I wonder if there is something I can do to go forward.

**Comment by alexp8** [comment]
The client doesn't have the space to support additional buttons.

You should instead apply these to custom maps

**Comment by LeuisKen** [comment]
> The client doesn't have the space to support additional buttons.

That's why I changed some of the height to make the style work: )

> You should instead apply these to custom maps

I do this a lot of times before I create this pr.

**Comment by LeuisKen** [comment]
@alexp8 Updated to fix merge conflicts. Hopefully, it could be merged.

**Comment by alexp8** [comment]
> The client doesn't have the space to support additional buttons.
> 
> You should instead apply these to custom maps

The client doesn't have the space to support additional buttons.

You should instead apply these to custom maps

**Comment by LeuisKen** [comment]
> > The client doesn't have the space to support additional buttons.
> 
> That's why I changed some of the height to make the style work: )
> 
> > You should instead apply these to custom maps
> 
> I do this a lot of times before I create this pr.

I already gave you my reason for your thoughts, why did you just repeat this while not responding to my feedback?

I think generating a lot of maps with these two new options is a pollution to the map db. As a developer I'm sure you understand what is "**Don't repeat yourself**", right?

Frankly speaking, I feel upset about your reply, but if you think that's the correct way for it then I will respect it.

**Comment by SadPencil** [comment]
> The client doesn't have the space to support additional buttons.
> 
> 
> 
> You should instead apply these to custom maps

I agree with the author. The author said he/she has already increased the height for more buttons. So perhaps it's better to provide a reason why increasing the height is not accepted, if the decision is closing this PR?

**Comment by pzhlkj6612** [comment]
Or maybe someone could upload a screenshot with the code in this PR, then we will know if the new added controls are OK or KO.

**Comment by alexp8** [comment]
> > The client doesn't have the space to support additional buttons.
> > You should instead apply these to custom maps
> 
> I agree with the author. The author said he/she has already increased the height for more buttons. So perhaps it's better to provide a reason why increasing the height is not accepted, if the decision is closing this PR?

we aren't going to keep adding buttons to the client, they can't all fit. If community is voicing a need for these buttons then we can add them but we aren't going to add buttons simply to satisfy this author where only he will use them

**Comment by alexp8** [comment]
There is also a concern of "instant build" being applied on maps where it would be considered 'cheating' by the original author.
Not sure we want this capability readily available on any map

**Comment by alexp8** [comment]
Overall it sounds like a very niche use case and as such should be applied on custom maps where it is needed

**Comment by pzhlkj6612** [comment]
OK, now that's more clear. I think that's not too much about UI design, but what options should be placed in the window. 

If we have the ability to specifying custom options applying to maps, we would be able to support customizing user experience for different players. Overriding map's settings for single play game sounds well to me.

**Pull request closed without merging**
